### ISSUE TITLE
Random times for new messages

### ISSUE THREAD

**Issue by DavidLarsKetch** [nss-day-cohort-23/group-project-chatty-keds#21]
## Expected Behavior
- Entering a message gives that message the current date & time

## Actual Behavior
- Entering a message gives that message a seemingly random time stamp

## Steps to Reproduce Behavior
- Enter a message

## Module Suspected / Relevant Files
- `date-reader.js`

**Comment by kenziebottoms** [comment]
12 noon == 12am; fix
